name: basketball
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - ipython
  - jupyter
  - click
  - tqdm
  - pandas
  - beautifulsoup4
  - lxml
  - html5lib
  - requests
  - matplotlib
  - seaborn
  - twine
  - flake8
  - mypy
  - pytest
  - wheel
  - pip
  - pip:
    - clickutil
    - nba_py
